services:

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./db.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pproductInSupermarket"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 15s
    ports:
      - 3306:3306

  mbti_express:
    build: ./backend
    image: mbti_express:1.0.0
    container_name: mbti_express
    restart: always
    env_file:
      - ./backend/.env
      - ./backend/docker.env
    ports:
      - 5175:5175
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
      backend_python:
        condition: service_started
  
  backend_python:
    build:
      context: ./backend-python
      dockerfile: dockerfile
    image: backend_python:1.0.0
    container_name: backend_python
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend-python:/app
  
  mbti_frontend:
    build: ./frontend
    image: supermarket_frontend:1.0.0
    container_name: supermarket_frontend
    restart: always
    env_file:
      - ./frontend/.env
      - ./frontend/docker.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - mbti_express

volumes:
  mysql_data:
