services:

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - ./backend/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: productInSupermarket
      MYSQL_DATABASE: mbti_db
    ports:
      - 3306:3306

  mbti_express:
    build: ./backend
    image: mbti_express:1.0.0
    container_name: mbti_express
    restart: always
    ports:
      - 5175:5175
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
  
  mbti_frontend:
    build: ./frontend
    image: supermarket_frontend:1.0.0
    container_name: supermarket_frontend
    restart: always
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - mbti_express